site_name: Chenxiao Mao
site_description: Notes on AI Systems, LLM Inference & Serving, Distributed Systems, and Modern AI.

theme:
  name: material

plugins:
  - search

markdown_extensions:
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Projects:
    - projects/index.md

  - Inference & Serving:
    - vLLM:
      - inference/vllm/index.md
      - Architecture:
        - Architecture: inference/vllm/architecture/arch-overview.md
        - vLLM Serve Startup: inference/vllm/architecture/vllm-serve-startup.md
        - vLLM Serve Request: inference/vllm/architecture/vllm-serve-request.md
      - Runtime:
        - vLLM Runtime Overview: inference/vllm/runtime/vllm-runtime.md
      - Memory System:
        - vLLM Memory System: inference/vllm/memory/vllm-memory.md
      - Distributed Inference:
        - vLLM Distributed: inference/vllm/distributed/vllm-distributed.md
      - Compiler:
        - vLLM Compiler: inference/vllm/compiler/vllm-compiler.md
      - Development:
        - Apple silicon CPU: inference/vllm/development/applesilicon-cpu.md
        - Apple silicon GPU: inference/vllm/development/applesilicon-gpu.md
        - vLLM Docker: inference/vllm/development/vllm-docker.md
        - vLLM Debug: inference/vllm/development/vllm-debug.md
        - vLLM C++: inference/vllm/development/vllm-cpp.md
        - vLLM Build: inference/vllm/development/vllm-build.md
        - vLLM Contributing: inference/vllm/development/vllm-contributing.md
      - Production:
        - Production Stack: inference/vllm/production/production-stack.md
    - SGLang:
      - inference/sglang/index.md

  - Model Fundamentals:
    - model/index.md
    - Transformer:
      - Tokenizer: model/transformer/tokenizer.md
    - DL:
      - Readings: model/dl/readings.md

  - AI Systems Overview:
    - Agent:
      - Overview: overview/agent/agent-overview.md
    - Accelerator:
      - Software Stack: overview/accelerator/software-stack.md
    - Tool:
      - AI Infra Engineer Toolbox: overview/tool/ai-infra-engineer-toolbox.md
